# Generated by Django 5.2.18 on 2026-10-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nucleo", "0003_catalogos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sucursal",
            options={"verbose_name": "sucursal", "verbose_name_plural": "sucursales"},
        ),
        migrations.AlterModelOptions(
            name="trabajador",
            options={
                "verbose_name": "trabajador",
                "verbose_name_plural": "trabajadores",
            },
        ),
        migrations.AlterModelOptions(
            name="unidad",
            options={"verbose_name": "unidad", "verbose_name_plural": "unidades"},
        ),
    ]
